address=/.naominet.jp/172.18.0.1
address=/.abs.sys-all.net/172.18.0.1
address=/.abs-link.sys-all.net/172.18.0.1
address=/.amlog.sys-all.net/172.18.0.1
address=/.apm.sys-all.net/172.18.0.1
address=/.test-abs.sys-all.net/172.18.0.1
