address=/.naominet.jp/127.0.0.1
address=/.abs.sys-all.net/127.0.0.1
address=/.abs-link.sys-all.net/127.0.0.1
address=/.amlog.sys-all.net/127.0.0.1
address=/.apm.sys-all.net/127.0.0.1
address=/.test-abs.sys-all.net/127.0.0.1
